Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,17 +1,49 @@
+name: Snyk SCA, Code, IaC and Container CLI monitor example
 
-name: workflow using Snyk with continue on error
-on: push
+on:
+  push:
+    branches: [ master ]
+  pull_request:
+    branches: [ master ]
+
 jobs:
-  security:
+  build:
+    name: Test and build
+    environment: snyk-npm
     runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@master
-  
-      - name: Run Snyk to check for vulnerabilities
-        uses: snyk/actions@0.3.0
-        with:
-         command: monitor
-         args: --all-projects --org=ninja-snyker --remote-repo-url=github-ci --json
-        continue-on-error: true
-        env:
-          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
+
+strategy:
+  matrix:
+    node-version: [16.x]
+
+    # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
+
+steps:
+  - uses: actions/checkout@v2
+  - name: Use Node.js ${{ matrix.node-version }}
+    uses: actions/setup-node@v2
+    with:
+      node-version: ${{ matrix.node-version }}
+      cache: 'npm'
+
+  - name: Setup Snyk + snyk-to-html # For information about the required commands for generating an HTML report see https://github.com/snyk/snyk-to-html
+    run: |
+      npm install snyk -g
+      npm install snyk-to-html -g
+      snyk auth ${{secrets.SNYK_AUTH}}
+
+  - name: Snyk Open Source # For testing and failing please add snyk test before snyk monitor
+    run: |
+      snyk monitor
+# For a list of additional available flags/options see: https://docs.snyk.io/snyk-cli/commands
+
+  - name: Snyk Code # Remove || true to fail if there are vulnerabilities
+    run: |
+      snyk code test || true
+  - name: Snyk Container # Rename your image, for testing and failing please add snyk container test before snyk container monitor
+    run: |
+      docker build . -t yourimage:tag
+      snyk container monitor yourimage:tag --file=Dockerfile
+  - name: Snyk IaC # Remove || true to fail if there are vulnerabilities
+    run: |
+      snyk iac test || true
